name: iKnowledge
pygments: true
encoding: UTF-8
permalink: /:year-:month-:day/:title/
markdown: redcarpet
include: ['.nojekyll', '.gitignore']
exclude: ['LICENSE', 'README.md']
destination: zzp-me.github.io
