name: iKnowledge
pygments: true
encoding: UTF-8
permalink: /:year-:month-:day/:title.html
include: ['.nojekyll']
exclude: ['LICENSE', 'README.md']
destination: redraiment.github.io
blog:
  name: 子清行
  motto: 黑夜中孤守一轮明月|喧闹中独享一份清闲
  url: zzp.me
author:
  id: redraiment
  name: 张泽鹏
  email: redraiment@gmail.com
